# Generated by Django 5.1 on 2024-10-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_signinout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signinout',
            name='salary_rate',
        ),
        migrations.AddField(
            model_name='customuser',
            name='salary_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Hourly rate in currency units', max_digits=6),
        ),
    ]
